### ISSUE TITLE
Windows Explorer stays open

### ISSUE THREAD

**Issue by LooNiEOG** [moudey/Shell#177] opened 2023-03-02 22:51 UTC
I thought this was fixed with the last update but apparently it is not. I do some work on my computer that requires me to have multiple instances of Windows Explorer open. Or I'll close some, reopen other windows in new explorers, etc. Potentially 20 times or more depending on what I'm doing. The issue arises when I go to task manager because my fans are loud and see that Windows Explorer.exe has 10-15 instances all taking up 3-10% of my CPU. I initially posted about this on Microsoft forums but they just gave their generic responses but recently someone posted a comment and said that the latest version of Shell fixed the issue. That does not seem to be the case sadly.

**Comment by moudey** [comment] 2023-03-03 15:19
>someone posted a comment and said that the latest version of Shell fixed the issue.

its me :)

There was a bug in version 1.7 when the explorer process finished and it was fixed in version 1.8.
Please uninstall Shell and try the explorer. If the issue persists, there will be a problem with the explorer.
If the issue is resolved after uninstalling Shell, let me know so we can continue fixing it.

**Comment by LooNiEOG** [comment] 2023-03-04 14:31
Uninstalling Shell did seem to make the issue go away. I can't replicate it no matter how many instances of explorer I open/close now.

**Closed** 2023-04-10 20:22 UTC
