### ISSUE TITLE
Visual studio code extension for syntax highlighting

### ISSUE THREAD

**Issue by StarNumber12046** [moudey/Shell#232] opened 2023-04-11 09:17 UTC
otherwise it is impossible to distinguish stuff

**Comment by moudey** [comment] 2023-04-14 02:32
#81

**Comment by moudey** [comment] 2023-04-14 02:39
Use any editor and apply the settings of any of these languages C/C++, C# or JS.

Duplicate of #81

**Closed** 2023-10-06 01:06 UTC
Labels: duplicate

**Comment by nathanpovo** [comment] 2024-05-10 18:43
An third-party extension can be found here https://marketplace.visualstudio.com/items?itemName=code-nature.nilesoft-shell-file-formatter

Source https://github.com/moudey/Shell/discussions/81#discussioncomment-6075891
